### ISSUE TITLE
Trajectory2d: informative method names

### ISSUE THREAD

**Issue by KrisC369** [hoangtungdinh/BebopRosJava#3]
> [Trajectory2d](https://github.com/hoangtungdinh/BebopRosJava/blob/develop/src/main/java/control/Trajectory2d.java) should have a more informative method names, because it can be used for not only x-y plane, but also x-z, y-z planes.

I can see why the x-y notation can be confusing when using this interface for x-z or y-z planes. 
I does give some impression of the meaning in the default 2D space that is conventionally defined as (x,y) coordinate system. 
The notation of 'first' and 'second' axis/plane is not better IMO. 

A valid alternative could be the use of (Abscissa,Ordinate)-notation, but it's maybe not easier. 
What do you think?

**Comment by hoangtungdinh** [comment]
I think Abscissa/Ordinate is fine. Thanks for updating.
