### ISSUE TITLE
Documentation absent for Trajectory4D

### ISSUE THREAD

**Issue by KrisC369** [hoangtungdinh/BebopRosJava#5]
There is no documentation for the Trajectory4D interface. 
Most methods in the interface are self-explanatory, but its not clear to me what the AngularZ actually represents or how it affects the movement in space. 
While implementing 4D motion primitives, this last aspect is hard to model correctly.

**Comment by hoangtungdinh** [comment]
Thanks, I updated the javadoc for getTrajectoryAngularZ()
